using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SAPLinks.Bussiness.SAPToBPMResult.SAPPurchase.SAP1
{
    public class PurchaseUpdate : AIncomePurchaseUpdate
    {
        public PurchaseUpdate(string connStr) : base(connStr)
        {
        }

        public override string UpdateSql(string company)
        {
            string query = @"USE [DABAN_BPM_{0}]
--更新最采购单
--1.先全部改成非最新单据
UPDATE [MAIN_PURCHASE_H] SET ISNEWESTXBLNR=0
--2.更新最新单据成1
UPDATE AA SET AA.ISNEWESTXBLNR=BB.ISNEWESTXBLNR FROM  [MAIN_PURCHASE_H] AA,(
--通过作业单+创建日期关联获得主键
SELECT BB.CXZBBB,1 ISNEWESTXBLNR FROM (
--根据日期取出采购单号最大正单，拼接出主键
SELECT CD,XBLNR,ZF,BSTZD,MAX(CREATEDATE) CREATEDATE FROM MAIN_PURCHASE_H
WHERE ZF=0 GROUP BY CD,XBLNR,ZF,BSTZD
) AA LEFT JOIN MAIN_PURCHASE_H BB ON AA.XBLNR=BB.XBLNR AND AA.CREATEDATE=BB.CREATEDATE
WHERE BB.ZF=0) BB 
WHERE AA.CXZBBB=BB.CXZBBB

--更新销售表外包金额、外包除税金额
--外包金额、外包除税
UPDATE AA SET AA.WBJE=BB.WBJE,AA.CSJE=BB.CSJE FROM [MAIN_PURCHASE_H] AA,(
 SELECT CXZBBB,XBLNR,SUM(WBJE) WBJE,SUM(CSJE) CSJE FROM (
 SELECT AA.CXZBBB,AA.XBLNR,ABS(BB.WRBTR) WBJE,0 CSJE FROM MAIN_PURCHASE_H AA
 LEFT JOIN MAIN_PURCHASE_I BB ON AA.CXZBBB=BB.CXZBBB
 WHERE BB.SAKNR='2121030000'-- GROUP BY AA.CXZBBB,AA.XBLNR
 UNION ALL
 SELECT AA.CXZBBB,AA.XBLNR,0 WBJE,ABS(BB.WRBTR) CSJE FROM MAIN_PURCHASE_H AA
 LEFT JOIN MAIN_PURCHASE_I BB ON AA.CXZBBB=BB.CXZBBB
 WHERE BB.SAKNR IN ('4101011501','4101011502') --GROUP BY AA.CXZBBB,AA.XBLNR
 ) AA GROUP BY CXZBBB,XBLNR
)BB WHERE AA.CXZBBB=BB.CXZBBB

--更新采购表供应商编码、名称
--先获得供应商编码
UPDATE AA SET AA.SUPP_CODE = BB.SUPPCODE FROM MAIN_PURCHASE_H AA,(
SELECT CXZBBB,ZUONR AS SUPPCODE FROM [DBO].[MAIN_PURCHASE_I] WHERE SAKNR='2121030000'
) BB WHERE AA.CXZBBB=BB.CXZBBB
--在获得供应商名称
UPDATE AA SET AA.SUPP_NAME = BB.SUPP_NAME FROM MAIN_PURCHASE_H AA,(SELECT SUPP_ID,SUPP_NAME FROM BPMDB.DBO.MAIN_SUPPLIER WHERE COMPANY='{0}') BB 
WHERE AA.SUPP_CODE=BB.SUPP_ID
--UPDATE AA SET AA.SUPP_NAME = BB.SUPP_NAME FROM MAIN_PURCHASE_H AA,(SELECT SAPCODE SUPP_ID,SUPP_ID SUPP_NAME FROM BPMDB.DBO.MAIN_OUTSOURCING_SUPPLIER WHERE COMPANY='{0}') BB 
--WHERE AA.SUPP_CODE=BB.SUPP_ID

--获取明细表4101011502的KOSTL字段
UPDATE AA SET AA.KOSTL=BB.KOSTL FROM MAIN_PURCHASE_H AA,(
SELECT CXZBBB,KOSTL FROM [DBO].[MAIN_PURCHASE_I] WHERE SAKNR='4101011502'
) BB WHERE AA.CXZBBB=BB.CXZBBB";
            return string.Format(query, company);
        }
    }
}
